# Generated by Django 5.2.9 on 2025-12-17 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Unique employee identification code', max_length=50, unique=True)),
                ('designation', models.CharField(help_text="Faculty designation/title (e.g., 'Assistant Professor')", max_length=100)),
                ('joining_date', models.DateField(help_text='Date when faculty joined the institution')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this faculty member is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account for this faculty member', on_delete=django.db.models.deletion.PROTECT, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
                'db_table': 'faculty_profiles',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='Day of the week (1=Monday, 7=Sunday)')),
                ('start_time', models.TimeField(help_text='Availability start time')),
                ('end_time', models.TimeField(help_text='Availability end time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this availability slot is currently active')),
                ('faculty', models.ForeignKey(help_text='Faculty member this availability belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Faculty Availability',
                'verbose_name_plural': 'Faculty Availabilities',
                'db_table': 'faculty_availabilities',
                'ordering': ['faculty', 'day_of_week', 'start_time'],
                'unique_together': {('faculty', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
