# Generated by Django 5.2.9 on 2025-12-17 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_coursesubject'),
        ('batch_management', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this assignment was created')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(help_text='Batch for which the subject is taught', on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to='batch_management.batch')),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned to teach', on_delete=django.db.models.deletion.PROTECT, related_name='subject_assignments', to='faculty.facultyprofile')),
                ('subject', models.ForeignKey(help_text='Subject assigned to the faculty', on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Faculty Assignment',
                'verbose_name_plural': 'Faculty Assignments',
                'db_table': 'faculty_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('faculty', 'batch', 'subject')},
            },
        ),
    ]
