# Generated by Django 4.2.8 on 2026-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULL_PAYMENT_VERIFIED', 'Full Payment Verified'), ('INSTALLMENT_VERIFIED', 'Installment Verified'), ('INSTALLMENT_PENDING', 'Installment Pending'), ('DISABLED', 'Disabled')], default='PENDING', help_text='Current admission status', max_length=30),
        ),
    ]
