# Generated by Django 6.0.2 on 2026-02-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_discovery_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULL_PAYMENT_VERIFIED', 'Full Payment Verified'), ('INSTALLMENT_VERIFIED', 'Installment Verified'), ('INSTALLMENT_PENDING', 'Installment Pending'), ('COURSE_COMPLETED', 'Course Completed'), ('DISABLED', 'Disabled')], default='PENDING', help_text='Current admission status', max_length=30),
        ),
    ]
