# Generated by Django 6.0.2 on 2026-02-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_refactor_admission_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='study_mode',
            field=models.CharField(choices=[('LIVE', 'Live')], default='LIVE', help_text='Preferred study mode (LIVE or RECORDED)', max_length=20),
        ),
    ]
