# Generated by Django 4.2.8 on 2026-02-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentprofile_study_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='referral_confirmed',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='referral_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='referral_confirmed_count',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='referred_by',
        ),
    ]
