# Generated by Django 5.2.9 on 2025-12-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's contact phone number", max_length=15, null=True),
        ),
    ]
