# Generated by Django 4.2.8 on 2026-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULL_PAYMENT', 'Full Payment Completed'), ('INSTALLMENT', 'Installment')], default='PENDING', help_text='Payment verification status', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULL_PAYMENT_VERIFIED', 'Full Payment Verified'), ('INSTALLMENT_VERIFIED', 'Installment Verified'), ('DISABLED', 'Disabled')], default='PENDING', help_text='Current admission status', max_length=30),
        ),
    ]
