# Generated by Django 4.2.8 on 2026-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_installment_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='study_mode',
            field=models.CharField(choices=[('LIVE', 'Live'), ('RECORDED', 'Recorded')],
                                   default='LIVE', help_text='Preferred study mode (LIVE or RECORDED)', max_length=20),
        ),
    ]
