# Generated by Django 5.2.9 on 2026-01-16 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_delete_subject_alter_coursemodule_unique_together'),
        ('batch_management', '0004_migrate_existing_mentor_assignments'),
        ('faculty', '0004_facultymoduleassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(help_text='Title of the topic/module', max_length=300)),
                ('topic_description', models.TextField(blank=True, help_text='Detailed description of the topic')),
                ('sequence_order', models.PositiveIntegerField(help_text='Order of this topic in the syllabus')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Estimated hours to cover this topic', max_digits=4)),
                ('planned_date', models.DateField(blank=True, help_text='Planned delivery date', null=True)),
                ('actual_date', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this topic has been completed')),
                ('resources', models.JSONField(blank=True, default=list, help_text='List of resource links/materials for this topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this course plan belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='course_plans', to='batch_management.batch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this plan entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_plans', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='Module this topic belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_plans', to='academics.module')),
            ],
            options={
                'verbose_name': 'Course Plan',
                'verbose_name_plural': 'Course Plans',
                'db_table': 'timetable_course_plans',
                'ordering': ['batch', 'module', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='Day of the week (1=Monday, 7=Sunday)')),
                ('start_time', models.TimeField(help_text='Class start time')),
                ('end_time', models.TimeField(help_text='Class end time')),
                ('room_number', models.CharField(blank=True, help_text='Physical room/classroom number (optional)', max_length=50)),
                ('default_meeting_link', models.URLField(blank=True, help_text='Default meeting link for online classes (Zoom/Meet/Teams)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this time slot belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='batch_management.batch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this time slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_slots', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(help_text='Faculty assigned to teach this slot', on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='faculty.facultyprofile')),
                ('module', models.ForeignKey(blank=True, help_text='Module taught in this time slot', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='academics.module')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'timetable_time_slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date of this class session')),
                ('actual_start_time', models.TimeField(blank=True, help_text='Actual class start time (if different from scheduled)', null=True)),
                ('actual_end_time', models.TimeField(blank=True, help_text='Actual class end time (if different from scheduled)', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', help_text='Current session status', max_length=20)),
                ('topic', models.CharField(blank=True, help_text='Topic covered in this session', max_length=500)),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting link for this specific session (overrides TimeSlot default)')),
                ('recording_link', models.URLField(blank=True, help_text='Recording link after session completion')),
                ('notes', models.TextField(blank=True, help_text='Session notes or remarks')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (if cancelled)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_plan', models.ForeignKey(blank=True, help_text='Linked course plan topic (FR-TIM-05)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='timetable.courseplan')),
                ('time_slot', models.ForeignKey(help_text='Time slot this session belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.timeslot')),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'db_table': 'timetable_class_sessions',
                'ordering': ['-session_date', 'time_slot__start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='courseplan',
            index=models.Index(fields=['batch', 'module'], name='timetable_c_batch_i_50302e_idx'),
        ),
        migrations.AddIndex(
            model_name='courseplan',
            index=models.Index(fields=['is_completed'], name='timetable_c_is_comp_2c8e92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseplan',
            unique_together={('batch', 'module', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['faculty', 'day_of_week'], name='timetable_t_faculty_4c1b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['batch', 'is_active'], name='timetable_t_batch_i_26bcb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('batch', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['session_date', 'status'], name='timetable_c_session_cf5f53_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['time_slot', 'session_date'], name='timetable_c_time_sl_1a4e33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('time_slot', 'session_date')},
        ),
    ]
