# Generated by Django 5.2.9 on 2026-02-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0006_delete_batchrecording'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['-session_date'], 'verbose_name': 'Class Session', 'verbose_name_plural': 'Class Sessions'},
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsession',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this session belongs to (for ad-hoc/recorded sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='batch_management.batch'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Time slot this session belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.timeslot'),
        ),
    ]
