# Generated by Django 5.2.9 on 2025-12-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Course name (e.g., 'Full Stack Web Development')", max_length=200, unique=True)),
                ('code', models.CharField(help_text="Unique course code (e.g., 'FSWD', 'DS', 'AIML')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed course description')),
                ('duration_months', models.PositiveIntegerField(help_text='Course duration in months')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
    ]
