# Generated by Django 5.2.9 on 2025-12-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_coursesubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this course-subject mapping is active'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='academics_courses',
        ),
        migrations.AlterModelTable(
            name='coursesubject',
            table='academics_course_subjects',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='academics_subjects',
        ),
    ]
