# Generated by Django 5.2.9 on 2025-12-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_course_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveIntegerField(default=6, help_text='Course duration in months (e.g., 6, 12, 24, 36)'),
        ),
    ]
