# Generated by Django 5.2.9 on 2026-01-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique module code (e.g., 'HTML', 'JS', 'REACT')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Module name (e.g., 'HTML & CSS Fundamentals')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed module description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this module is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'academics_modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(help_text='Order of this module in the course curriculum')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course-module mapping is active')),
                ('course', models.ForeignKey(help_text='Course this module belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='course_modules', to='academics.course')),
                ('module', models.ForeignKey(help_text='Module included in the course', on_delete=django.db.models.deletion.PROTECT, related_name='course_modules', to='academics.module')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'db_table': 'academics_course_modules',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.DeleteModel(
            name='CourseSubject',
        ),
    ]
