# Generated by Django 5.2.9 on 2026-01-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_module_coursemodule_delete_coursesubject'),
        ('faculty', '0004_facultymoduleassignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'module')},
        ),
    ]
