# Generated by Django 6.0.2 on 2026-02-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0007_batchrecordedsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtemplate',
            name='mode',
            field=models.CharField(choices=[('LIVE', 'Live')], help_text='Delivery mode (Live or Recorded)', max_length=20),
        ),
    ]
