# Generated by Django 4.2.8 on 2026-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0008_alter_batchtemplate_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='meeting_link',
            field=models.URLField(blank=True, default='', help_text='Common meeting link for all classes in this batch (Zoom/Meet/Teams)'),
        ),
    ]
