# Generated by Django 4.2.8 on 2026-02-05 04:04

import apps.assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_assignments_batch_i_5b0f19_idx_assignments_batch_i_6bddf4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, help_text='Optional reference material or assignment document (PDF, DOC, DOCX, ZIP max 10MB)', null=True, upload_to=apps.assignments.models.faculty_assignment_upload_path),
        ),
    ]
