# Generated by Django 5.2.9 on 2026-02-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_classsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['-session_date', 'time_slot__start_time'], 'verbose_name': 'Class Session', 'verbose_name_plural': 'Class Sessions'},
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('time_slot', 'session_date')},
        ),
        migrations.AlterField(
            model_name='classsession',
            name='time_slot',
            field=models.ForeignKey(help_text='Time slot this session belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.timeslot'),
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='batch',
        ),
    ]
