# Generated by Django 6.0 on 2026-02-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_batch_i_6bddf4_idx',
            old_name='assignments_batch_i_5b0f19_idx',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_faculty_4fa786_idx',
            old_name='assignments_faculty_dbc0dd_idx',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_due_dat_708d3b_idx',
            old_name='assignments_due_dat_e98df6_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentsubmission',
            new_name='assignment__assignm_c9693f_idx',
            old_name='assignment_assignm_e43fc9_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentsubmission',
            new_name='assignment__student_f0cb4e_idx',
            old_name='assignment_student_35f6dd_idx',
        ),
    ]
