# Generated by Django 5.2.9 on 2026-02-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_questionbank_bankquestion'),
        ('assignments', '0005_assignment_skill_mapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentskillmapping',
            name='unique_assignment_skill',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_start_d_453408_idx',
            old_name='assignment_start_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assignmentskillmapping',
            unique_together={('assignment', 'skill')},
        ),
    ]
