# Generated by Django 4.2.8 on 2026-01-22 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_add_installment_pending_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], help_text='Attendance status (Present/Absent)', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True, help_text='Timestamp when attendance was last marked/updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when attendance was first created')),
                ('marked_by', models.ForeignKey(help_text='Faculty who marked this attendance', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The class session this attendance is for', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='timetable.classsession')),
                ('student', models.ForeignKey(help_text='The student this attendance record is for', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['session', 'student'],
                'indexes': [models.Index(fields=['session', 'status'], name='attendance__session_523367_idx'), models.Index(fields=['student', 'status'], name='attendance__student_cdd655_idx'), models.Index(fields=['marked_by', 'marked_at'], name='attendance__marked__ecb83b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_session_student_attendance'),
        ),
    ]
