# Generated by Django 5.2.9 on 2025-12-17 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('audit', '0001_initial'),
        ('centres', '0002_create_default_centre'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (e.g., FSWD Live Template)', max_length=100)),
                ('mode', models.CharField(choices=[('LIVE', 'Live'), ('RECORDED', 'Recorded')], help_text='Delivery mode (Live or Recorded)', max_length=20)),
                ('max_students', models.PositiveIntegerField(help_text='Maximum number of students allowed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this template is for', on_delete=django.db.models.deletion.PROTECT, related_name='batch_templates', to='academics.course')),
            ],
            options={
                'verbose_name': 'Batch Template',
                'verbose_name_plural': 'Batch Templates',
                'db_table': 'batch_templates',
                'ordering': ['name'],
                'unique_together': {('course', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Auto-generated unique batch code', max_length=50, unique=True)),
                ('start_date', models.DateField(help_text='Batch start date')),
                ('end_date', models.DateField(help_text='Batch end date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current batch status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this batch is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(help_text='Centre this batch belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='centres.centre')),
                ('template', models.ForeignKey(help_text='Template this batch was created from', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='batch_management.batchtemplate')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for transfer')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, help_text='When the transfer occurred')),
                ('audit_log', models.ForeignKey(blank=True, help_text='Linked audit log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_transfers', to='audit.auditlog')),
                ('from_batch', models.ForeignKey(help_text='Source batch', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='batch_management.batch')),
                ('student', models.ForeignKey(help_text='Student being transferred', on_delete=django.db.models.deletion.PROTECT, related_name='batch_transfers', to='students.studentprofile')),
                ('to_batch', models.ForeignKey(help_text='Destination batch', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='batch_management.batch')),
                ('transferred_by', models.ForeignKey(blank=True, help_text='Admin who performed the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_transfers_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Transfer Log',
                'verbose_name_plural': 'Batch Transfer Logs',
                'db_table': 'batch_transfer_logs',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When student joined this batch')),
                ('left_at', models.DateTimeField(blank=True, help_text='When student left this batch (if applicable)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this enrollment is currently active')),
                ('batch', models.ForeignKey(help_text='Batch the student is enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='batch_management.batch')),
                ('student', models.ForeignKey(help_text='Student enrolled in this batch', on_delete=django.db.models.deletion.PROTECT, related_name='batch_memberships', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Batch Student',
                'verbose_name_plural': 'Batch Students',
                'db_table': 'batch_students',
                'ordering': ['batch', 'joined_at'],
                'unique_together': {('batch', 'student')},
            },
        ),
    ]
