# Generated by Django 4.2.8 on 2025-12-30 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='Batch mentor assigned to this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
