# Generated by Django 4.2.8 on 2025-12-31 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch_management', '0002_batch_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the mentor was assigned to this batch')),
                ('unassigned_at', models.DateTimeField(blank=True, help_text='When the mentor was unassigned from this batch', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(help_text='The batch the mentor is assigned to', on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to='batch_management.batch')),
                ('mentor', models.ForeignKey(help_text='The mentor assigned to the batch', on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Mentor Assignment',
                'verbose_name_plural': 'Batch Mentor Assignments',
                'db_table': 'batch_mentor_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='batchmentorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('batch',), name='unique_active_mentor_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='batchmentorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('mentor',), name='unique_active_batch_per_mentor'),
        ),
    ]
