# Generated by Django 4.2.8 on 2025-12-31 06:14

from django.db import migrations


def migrate_mentor_assignments(apps, schema_editor):
    """
    Migrate existing mentor assignments from Batch.mentor to BatchMentorAssignment table.
    This preserves existing data while transitioning to the new ERP-grade assignment system.
    """
    Batch = apps.get_model('batch_management', 'Batch')
    BatchMentorAssignment = apps.get_model('batch_management', 'BatchMentorAssignment')
    
    # Get all batches that have a mentor assigned via the old FK
    batches_with_mentors = Batch.objects.filter(mentor__isnull=False)
    
    for batch in batches_with_mentors:
        # Check if an active assignment already exists (shouldn't, but be safe)
        existing = BatchMentorAssignment.objects.filter(
            batch=batch,
            is_active=True
        ).exists()
        
        if not existing:
            # Create a new assignment record
            BatchMentorAssignment.objects.create(
                mentor_id=batch.mentor_id,
                batch=batch,
                is_active=True,
                # assigned_by will be null since this is a migration
            )
            print(f"Migrated mentor assignment for batch {batch.code}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - nothing to do since we're not deleting the Batch.mentor FK.
    The BatchMentorAssignment records will be deleted when the table is dropped.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0003_add_batch_mentor_assignment'),
    ]

    operations = [
        migrations.RunPython(migrate_mentor_assignments, reverse_migration),
    ]
