# Generated by Django 5.2.9 on 2026-02-09 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0004_migrate_existing_mentor_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the recording/class', max_length=255)),
                ('recording_url', models.URLField(help_text='URL to the recording')),
                ('date', models.DateField(help_text='Date of the class')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this recording belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='batch_management.batch')),
            ],
            options={
                'verbose_name': 'Batch Recording',
                'verbose_name_plural': 'Batch Recordings',
                'db_table': 'batch_recordings',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
