# Generated by Django 5.2.9 on 2026-02-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0005_batchrecording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchRecording',
        ),
    ]
