# Generated by Django 5.2.9 on 2026-02-10 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_management', '0006_delete_batchrecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecordedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date of the recorded session')),
                ('meeting_topic', models.CharField(help_text='Topic/title of the meeting', max_length=200)),
                ('recording_link', models.URLField(help_text='URL to the recorded meeting (YouTube, Zoom, etc.)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recorded_sessions', to='batch_management.batch')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Mentor who uploaded this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Recorded Session',
                'verbose_name_plural': 'Batch Recorded Sessions',
                'db_table': 'batch_recorded_sessions',
                'ordering': ['-session_date', '-created_at'],
                'indexes': [models.Index(fields=['batch', '-session_date'], name='batch_recor_batch_i_e38e43_idx')],
            },
        ),
    ]
