# Generated by Django 5.2.9 on 2026-02-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
        ('students', '0005_studentprofile_study_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_link', models.URLField(help_text='The registration link sent to student', max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the link was sent to student')),
            ],
            options={
                'verbose_name': 'Student Placement Link',
                'verbose_name_plural': 'Student Placement Links',
                'db_table': 'student_placement_links',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='placementliststudent',
            name='placement_l_placeme_428502_idx',
        ),
        migrations.AddField(
            model_name='placementlist',
            name='placement_link',
            field=models.URLField(blank=True, help_text='Registration link for students to apply for placement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentplacementlink',
            name='placement_list',
            field=models.ForeignKey(help_text='The placement list with the link', on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='placement.placementlist'),
        ),
        migrations.AddField(
            model_name='studentplacementlink',
            name='student',
            field=models.ForeignKey(help_text='Student who received the link', on_delete=django.db.models.deletion.CASCADE, related_name='placement_links', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='studentplacementlink',
            unique_together={('student', 'placement_list')},
        ),
    ]
