# Generated by Django 5.2.9 on 2026-02-02 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_studentprofile_study_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the placement list', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this placement list')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this placement list was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this placement list is currently active')),
                ('created_by', models.ForeignKey(help_text='User who created this placement list', on_delete=django.db.models.deletion.PROTECT, related_name='created_placement_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement List',
                'verbose_name_plural': 'Placement Lists',
                'db_table': 'placement_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementListStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this student for placement')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this student was added to the list')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this student is currently in the list')),
                ('added_by', models.ForeignKey(help_text='User who added this student to the list', on_delete=django.db.models.deletion.PROTECT, related_name='added_placement_students', to=settings.AUTH_USER_MODEL)),
                ('placement_list', models.ForeignKey(help_text='The placement list this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='placement.placementlist')),
                ('student', models.ForeignKey(help_text='The student in this placement list', on_delete=django.db.models.deletion.CASCADE, related_name='placement_lists', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Placement List Student',
                'verbose_name_plural': 'Placement List Students',
                'db_table': 'placement_list_students',
                'ordering': ['added_at'],
                'indexes': [models.Index(fields=['placement_list', 'is_active'], name='placement_l_placeme_428502_idx')],
                'unique_together': {('placement_list', 'student')},
            },
        ),
    ]
