# Generated by Django 5.2.9 on 2026-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_studentplacementlink_and_more'),
        ('students', '0005_studentprofile_study_mode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentplacementlink',
            index=models.Index(fields=['placement_list', 'student'], name='student_pla_placeme_79dff9_idx'),
        ),
    ]
