# Generated by Django 4.2.8 on 2026-01-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_courses',
            field=models.CharField(blank=True, help_text='Courses the user is interested in', max_length=500),
        ),
    ]
