# Generated by Django 6.0 on 2026-01-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skill names evaluated by this assessment (from Course skills)'),
        ),
    ]
