# Generated by Django 4.2.8 on 2026-01-28 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0004_facultymoduleassignment_and_more'),
        ('academics', '0007_delete_subject_alter_coursemodule_unique_together'),
        ('students', '0005_studentprofile_study_mode'),
        ('batch_management', '0004_migrate_existing_mentor_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assessment title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions')),
                ('total_marks', models.PositiveIntegerField(help_text='Total marks for this assessment', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_percentage', models.PositiveIntegerField(default=40, help_text='Minimum percentage required to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_time', models.DateTimeField(help_text='When the assessment becomes available')),
                ('end_time', models.DateTimeField(help_text='When the assessment closes')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', help_text='Current assessment status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this assessment is for', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='batch_management.batch')),
                ('faculty', models.ForeignKey(help_text='Faculty who created this assessment', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='faculty.facultyprofile')),
                ('subject', models.ForeignKey(help_text='Subject/Module this assessment covers', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.module')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Option label (A, B, C, D)', max_length=1)),
                ('option_text', models.TextField(help_text='The option text')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
            ],
            options={
                'verbose_name': 'Assessment Option',
                'verbose_name_plural': 'Assessment Options',
                'db_table': 'assessment_options',
                'ordering': ['option_label'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('marks', models.PositiveIntegerField(help_text='Marks for this question', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the question')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(help_text='Assessment this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'assessment_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Skill name (e.g., 'Python Basics', 'Data Structures')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Skill description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this skill is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this skill belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_skills', to='academics.course')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the attempt started')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the attempt was submitted', null=True)),
                ('total_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total marks obtained', max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated')], default='IN_PROGRESS', help_text='Current attempt status', max_length=20)),
                ('assessment', models.ForeignKey(help_text='Assessment being attempted', on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('student', models.ForeignKey(help_text='Student who made this attempt', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_attempts', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Assessment Attempt',
                'verbose_name_plural': 'Student Assessment Attempts',
                'db_table': 'student_assessment_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether the answer is correct (set during evaluation)', null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, help_text='Marks obtained for this answer', max_digits=5)),
                ('attempt', models.ForeignKey(help_text='Attempt this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.studentassessmentattempt')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='assessments.assessmentquestion')),
                ('selected_option', models.ForeignKey(blank=True, help_text='Option selected by student (null if unanswered)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_selections', to='assessments.assessmentoption')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'db_table': 'student_answers',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.PositiveIntegerField(help_text='Weight of this skill in the assessment (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('assessment', models.ForeignKey(help_text='Assessment being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='assessments.assessment')),
                ('skill', models.ForeignKey(help_text='Skill being evaluated', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_mappings', to='assessments.skill')),
            ],
            options={
                'verbose_name': 'Assessment Skill Mapping',
                'verbose_name_plural': 'Assessment Skill Mappings',
                'db_table': 'assessment_skill_mappings',
            },
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='question',
            field=models.ForeignKey(help_text='Question this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentquestion'),
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_score', models.DecimalField(decimal_places=2, default=0, help_text='Aggregated percentage score for this skill', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.CharField(choices=[('NOT_ACQUIRED', 'Not Acquired'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='NOT_ACQUIRED', help_text='Current skill level', max_length=20)),
                ('attempts_count', models.PositiveIntegerField(default=0, help_text='Number of assessments contributing to this skill')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this skill was last updated')),
                ('skill', models.ForeignKey(help_text='The skill being tracked', on_delete=django.db.models.deletion.PROTECT, related_name='student_skills', to='assessments.skill')),
                ('student', models.ForeignKey(help_text='Student this skill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Skill',
                'verbose_name_plural': 'Student Skills',
                'db_table': 'student_skills',
                'ordering': ['skill__name'],
                'indexes': [models.Index(fields=['student', 'level'], name='student_ski_student_ee70c6_idx')],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.AddIndex(
            model_name='studentassessmentattempt',
            index=models.Index(fields=['student', 'status'], name='student_ass_student_e1f2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessmentattempt',
            index=models.Index(fields=['assessment', 'status'], name='student_ass_assessm_7f9dba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentassessmentattempt',
            unique_together={('student', 'assessment')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('course', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentskillmapping',
            unique_together={('assessment', 'skill')},
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['assessment', 'order'], name='assessment__assessm_de4fc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentoption',
            unique_together={('question', 'option_label')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['batch', 'status'], name='assessments_batch_i_642870_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['faculty', 'status'], name='assessments_faculty_d68c94_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['start_time', 'end_time'], name='assessments_start_t_265046_idx'),
        ),
    ]
