# Generated by Django 4.2.8 on 2026-01-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_facultymoduleassignment_and_more'),
        ('academics', '0007_delete_subject_alter_coursemodule_unique_together'),
        ('assessments', '0002_add_skills_json_to_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the question bank', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty who created this bank', on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='faculty.facultyprofile')),
                ('subject', models.ForeignKey(help_text='Subject/Module this bank is for', on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='academics.module')),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'db_table': 'question_banks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('option_a', models.TextField(help_text='Option A text')),
                ('option_b', models.TextField(help_text='Option B text')),
                ('option_c', models.TextField(help_text='Option C text')),
                ('option_d', models.TextField(help_text='Option D text')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The correct answer (A, B, C, or D)', max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(help_text='Question bank this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionbank')),
            ],
            options={
                'verbose_name': 'Bank Question',
                'verbose_name_plural': 'Bank Questions',
                'db_table': 'bank_questions',
                'ordering': ['id'],
            },
        ),
    ]
