# Generated by Django 5.2.9 on 2025-12-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique subject code (e.g., 'HTML', 'JS', 'REACT')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Subject name (e.g., 'HTML & CSS Fundamentals')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed subject description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(help_text='Order of this subject in the course curriculum')),
                ('course', models.ForeignKey(help_text='Course this subject belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='course_subjects', to='academics.course')),
                ('subject', models.ForeignKey(help_text='Subject included in the course', on_delete=django.db.models.deletion.PROTECT, related_name='course_subjects', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Course Subject',
                'verbose_name_plural': 'Course Subjects',
                'db_table': 'course_subjects',
                'ordering': ['sequence_order'],
                'unique_together': {('course', 'subject')},
            },
        ),
    ]
