# Generated by Django 5.2.9 on 2025-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_course_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills gained after completing the course (stored as list of strings)'),
        ),
    ]
