# Generated by Django 5.2.9 on 2025-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Permission code (e.g., 'view_student_profile')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Human-readable description')),
                ('module', models.CharField(blank=True, help_text='Module/feature this permission belongs to', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this permission active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'rbac_permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role name (e.g., 'Student', 'Faculty')", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique role code (e.g., 'STUDENT', 'FACULTY')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Is this role active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'rbac_role_permissions',
                'ordering': ['role', 'permission'],
            },
        ),
    ]
