# Generated by Django 5.2.9 on 2025-12-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed (e.g., 'user.created', 'user.status_changed')", max_length=100)),
                ('entity', models.CharField(help_text="Type of entity affected (e.g., 'User', 'Role')", max_length=100)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=100)),
                ('details', models.JSONField(blank=True, help_text='Additional details about the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['entity', 'entity_id'], name='audit_logs_entity_22e216_idx'), models.Index(fields=['performed_by'], name='audit_logs_perform_30f9f7_idx')],
            },
        ),
    ]
