# Generated by Django 4.2.8 on 2026-01-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_interested_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('FULL', 'Full Payment'), ('INSTALLMENT', 'Installment')], help_text='Preferred payment method', max_length=50),
        ),
    ]
