# Generated by Django 5.2.9 on 2026-01-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_module_coursemodule_delete_coursesubject'),
        ('faculty', '0003_facultybatchassignment_facultysubjectassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this assignment was created')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_module_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned to teach this module', on_delete=django.db.models.deletion.PROTECT, related_name='module_assignments', to='faculty.facultyprofile')),
                ('module', models.ForeignKey(help_text='Module assigned to the faculty', on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to='academics.module')),
            ],
            options={
                'verbose_name': 'Faculty Module Assignment',
                'verbose_name_plural': 'Faculty Module Assignments',
                'db_table': 'faculty_module_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('faculty', 'module')},
            },
        ),
        migrations.DeleteModel(
            name='FacultySubjectAssignment',
        ),
    ]
