# Generated by Django 6.0 on 2026-02-09 17:46

import apps.course_materials.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_delete_subject_alter_coursemodule_unique_together'),
        ('batch_management', '0004_migrate_existing_mentor_assignments'),
        ('faculty', '0004_facultymoduleassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Material title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the material')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PPT / PPTX'), ('DOC', 'DOC / DOCX'), ('VIDEO', 'Video'), ('LINK', 'External Link')], help_text='Type of material', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (PDF, PPT, DOC). Max 20 MB.', null=True, upload_to=apps.course_materials.models.course_material_upload_path)),
                ('external_url', models.URLField(blank=True, help_text='External URL (for VIDEO / LINK types)', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty who uploaded the material', on_delete=django.db.models.deletion.PROTECT, related_name='course_materials', to='faculty.facultyprofile')),
                ('module', models.ForeignKey(help_text='Module this material belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='course_materials', to='academics.module')),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'db_table': 'course_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this batch mapping is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='Batch that has access to this material', on_delete=django.db.models.deletion.PROTECT, related_name='material_assignments', to='batch_management.batch')),
                ('material', models.ForeignKey(help_text='The course material', on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='course_materials.coursematerial')),
            ],
            options={
                'verbose_name': 'Course Material Batch',
                'verbose_name_plural': 'Course Material Batches',
                'db_table': 'course_material_batches',
                'ordering': ['-created_at'],
                'unique_together': {('material', 'batch')},
            },
        ),
    ]
